#!/bin bash

#
# gpsposition
# python script wrapper for gpsposition.py
#
# Version 1.0a
#
# Steve de Bode - KQ4ZCI - December 2025
#

source "$DigiHubvenv/bin/activate"
gpsposition=$($DigiHubPy/gpsposition.py)
IFS=',' read -r lat lon <<< "$gpsposition"
hamgrid=$($DigiHubPy/hamgrid.py "$lat" "$lon")
IFS=',' read -r grid <<< "$hamgrid"
deactivate

printf  '\nCurrent Location: Latitude: %s Longitude: %s Grid: %s\n\n' "$lat" "$lon" "$grid"